name: Validate PR

on:
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Java (Firestore emulator)
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test (in-memory)
        run: pnpm test

      - name: Start Firebase Emulator
        uses: invertase/firebase-emulator-action@v1.0.1
        with:
          firebase-tools-version: "latest"
          emulators: "firestore"
          project-id: "test-project"
          check-port: "8080"
      - name: Test (Firestore emulator)
        run: pnpm run test:emulator

      - name: Build
        run: pnpm build
